### ISSUE TITLE
Compilation problems for iOS

### ISSUE THREAD

**Issue by dcaplopu** [xtremekforever/swift-rabbitmq#20]
Hi.

I want to try your lib but it does not compile for iOS.

Can you modify the Package.swift to be able to compile it?

<img width="780" alt="Screenshot 2024-12-18 at 16 39 52" src="https://github.com/user-attachments/assets/0713259b-4e77-4b5d-8158-e908435d7502" />

Regards.

**Comment by xtremekforever** [comment]
Cool, I didn't know people would want to use this from iOS. Let me have a look.

**Comment by xtremekforever** [comment]
@dcaplopu I added some minimum versions to Package.swift- can you try it out on the main branch and see if it works?

https://github.com/xtremekforever/swift-rabbitmq/commit/f02219c8a02f415bf0c136bcbd9de02e33159f93

If so I can tag a new release with the fix.

**Comment by dcaplopu** [comment]
I have added the repo URL to the Swift package manager. How can I point to
the branch?

**Comment by xtremekforever** [comment]
@dcaplopu just remove it, and re-add it while selecting "Branch" for the dependency rule and put in the `main` branch, like this:

<img width="1590" alt="image" src="https://github.com/user-attachments/assets/19d98d99-973a-47b5-b284-7fcf5ae423db" />

**Comment by dcaplopu** [comment]
Hi.

Now compilation fails with:

![Screenshot 2024-12-19 at 08 23 21](https://github.com/user-attachments/assets/52c2c446-080c-4ad3-809b-6a6287cf1ef4)

**Comment by xtremekforever** [comment]
Okay. Let me have a look...

**Comment by dcaplopu** [comment]
Maybe you need to set min iOS version .16 instead of .13.

**Comment by jessezamora** [comment]
Yep, I've updated the minimum iOS version to 17 (required for `withThrowingDiscardingTaskGroup`) and pushed this to main. You can give it a shot now if you like. I was waiting to see if the swift-package-index would be able to build it for iOS successfully.

**Comment by dcaplopu** [comment]
It compiles now. Thank you.

**Comment by xtremekforever** [comment]
Enjoy!
